### ISSUE TITLE
表示の改善

### ISSUE THREAD

**Issue by c0b21007** [C0B21175/ProjExD#4]
https://github.com/C0B21175/ProjExD/blob/b5a6dbf4c5e09f02f15ee96c5774a5f04508d5f2/ex02/calc.py#L50
電卓の画面に「**0.5」や「**2」とするよりも、「√」などと表記して押した瞬間に計算結果が表示されるようにしたほうがきれいだと思います。

**Comment by C0B21175** [comment]
ボタンを押したときに置き換えることで変更しました。
